# Appveyor configuration template for Rust
# https://github.com/starkat99/appveyor-rust

# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2015

install:
  - ps: .\appveyor_rust_install.ps1 -channel stable -target x86_64-pc-windows-msvc

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false

test_script:
  - cmd: cargo build
